import { jsPDF } from 'jspdf'

export function exportTenderPDF(tender) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const L = 20
  const R = 190
  const W = R - L
  let y = 20

  const line = (color = [226, 232, 240]) => {
    doc.setDrawColor(...color)
    doc.setLineWidth(0.3)
    doc.line(L, y, R, y)
    y += 5
  }

  const text = (str, x, size = 10, style = 'normal', color = [30, 41, 59]) => {
    doc.setFontSize(size)
    doc.setFont('helvetica', style)
    doc.setTextColor(...color)
    doc.text(str, x, y)
  }

  const wrap = (str, x, maxW, size = 9) => {
    doc.setFontSize(size)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(71, 85, 105)
    const lines = doc.splitTextToSize(str, maxW)
    doc.text(lines, x, y)
    y += lines.length * 4.5
  }

  // Header bar
  doc.setFillColor(15, 23, 42)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text('INVITATION TO TENDER', L, 13)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(148, 163, 184)
  doc.text('AI Tender Management System  ·  Confidential Document', L, 20)
  y = 38

  // Tender ID badge area
  doc.setFillColor(239, 246, 255)
  doc.roundedRect(L, y - 5, W, 14, 2, 2, 'F')
  text(tender.id, L + 4, 11, 'bold', [37, 99, 235])
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 116, 139)
  doc.text(`Stage: ${tender.stage}`, R - 4, y + 2, { align: 'right' })
  y += 16

  // Title
  text(tender.title, L, 14, 'bold', [15, 23, 42])
  y += 8
  text(`${tender.department}`, L, 9, 'normal', [100, 116, 139])
  y += 8
  line()

  // Key Details grid
  const fields = [
    ['Budget', tender.budget],
    ['Submission Deadline', tender.deadline],
    ['Created', tender.created],
    ['Bidders', String(tender.bidders ?? 0)],
    ...(tender.duration ? [['Contract Duration', tender.duration]] : []),
  ]

  text('KEY DETAILS', L, 8, 'bold', [100, 116, 139])
  y += 6
  const col = W / 2
  fields.forEach((f, i) => {
    const x = i % 2 === 0 ? L : L + col
    if (i % 2 === 0 && i > 0) y += 9
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 116, 139)
    doc.text(f[0].toUpperCase(), x, y)
    doc.setFontSize(9.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 41, 59)
    doc.text(f[1], x, y + 4)
  })
  y += 14
  line()

  // Description
  if (tender.description) {
    text('DESCRIPTION', L, 8, 'bold', [100, 116, 139])
    y += 6
    wrap(tender.description, L, W)
    y += 4
    line()
  }

  // Scope section
  text('SCOPE OF WORK', L, 8, 'bold', [100, 116, 139])
  y += 6
  const scope = `The Contractor shall provide ${tender.title} for ${tender.department}, encompassing the full design, implementation, testing, and handover of all required deliverables as specified in this Invitation to Tender. The scope includes procurement, installation, integration, user acceptance testing, staff training, and ongoing support and maintenance as per agreed SLA terms.`
  wrap(scope, L, W)
  y += 2
  line()

  // Evaluation criteria
  text('EVALUATION CRITERIA', L, 8, 'bold', [100, 116, 139])
  y += 6
  const criteria = [
    ['Technical Approach & Methodology', '25%'],
    ['Team Qualifications & Experience', '20%'],
    ['Implementation Timeline', '15%'],
    ['Total Bid Price', '40%'],
  ]
  criteria.forEach(([label, weight]) => {
    doc.setFillColor(248, 250, 252)
    doc.rect(L, y - 3, W, 7, 'F')
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(51, 65, 85)
    doc.text(label, L + 3, y + 1)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(37, 99, 235)
    doc.text(weight, R - 3, y + 1, { align: 'right' })
    y += 8
  })
  y += 2
  line()

  // Footer
  doc.setFillColor(248, 250, 252)
  doc.rect(0, 277, 210, 20, 'F')
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(148, 163, 184)
  doc.text(`Generated by TenderAI  ·  ${tender.id}  ·  ${new Date().toLocaleDateString('en-GB')}`, 105, 287, { align: 'center' })

  doc.save(`${tender.id}-ITT.pdf`)
}

function reportShell(tender, headerTitle) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const L = 20
  const R = 190
  const W = R - L
  let y = 20

  doc.setFillColor(15, 23, 42)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text(headerTitle, L, 13)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(148, 163, 184)
  doc.text('AI Tender Management System  ·  Confidential Document', L, 20)
  y = 38

  doc.setFillColor(239, 246, 255)
  doc.roundedRect(L, y - 5, W, 14, 2, 2, 'F')
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(37, 99, 235)
  doc.text(tender.id, L + 4, y + 2)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 116, 139)
  doc.text(`Stage: ${tender.stage}`, R - 4, y + 2, { align: 'right' })
  y += 16

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(15, 23, 42)
  doc.text(tender.title, L, y)
  y += 8
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 116, 139)
  doc.text(tender.department, L, y)
  y += 8
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.3)
  doc.line(L, y, R, y)
  y += 8

  return { doc, L, R, W, y }
}

function reportFooter(doc, tender) {
  doc.setFillColor(248, 250, 252)
  doc.rect(0, 277, 210, 20, 'F')
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(148, 163, 184)
  doc.text(`Generated by TenderAI  ·  ${tender.id}  ·  ${new Date().toLocaleDateString('en-GB')}`, 105, 287, { align: 'center' })
}

export function exportPreQualSummaryPDF(tender, qualifiedBidders) {
  const { doc, L, R, W } = reportShell(tender, 'PRE-QUALIFICATION SUMMARY')
  let y = 78

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(100, 116, 139)
  doc.text('FINANCIALLY QUALIFIED BIDDERS', L, y)
  y += 6

  qualifiedBidders.forEach((b, i) => {
    doc.setFillColor(i === 0 ? 236 : 248, i === 0 ? 253 : 250, i === 0 ? 245 : 252)
    doc.rect(L, y - 4, W, 9, 'F')
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.text(`${i + 1}. ${b.name}`, L + 3, y + 1.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(71, 85, 105)
    doc.text(`${b.country} · Financial: ${b.stage4?.result || 'PASS'}`, R - 3, y + 1.5, { align: 'right' })
    y += 10
  })

  reportFooter(doc, tender)
  doc.save(`${tender.id}-PreQual-Summary.pdf`)
}

export function exportClosureReportPDF(tender) {
  const { doc, L, W } = reportShell(tender, 'CONTRACT CLOSURE REPORT')
  let y = 78

  const fields = [
    ['Contract Start', tender.contractStartDate || '—'],
    ['Delivery Progress', `${tender.deliveryProgress ?? 100}%`],
    ['Final Budget', tender.budget],
    ['Closure Date', new Date().toLocaleDateString('en-GB')],
  ]
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(100, 116, 139)
  doc.text('CLOSURE DETAILS', L, y)
  y += 7
  fields.forEach(([label, value]) => {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 116, 139)
    doc.text(label, L, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.text(String(value), L + W, y, { align: 'right' })
    y += 7
  })

  reportFooter(doc, tender)
  doc.save(`${tender.id}-Closure-Report.pdf`)
}
