import { jsPDF } from 'jspdf'
import { tenderRef } from './tenderRef'
import { PSF_HEADER_FIELDS, PSF_NARRATIVE_FIELDS, EM_DASH } from '../data/psfTemplate'

export function exportTenderPDF(tender) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const L = 20
  const R = 190
  const W = R - L
  let y = 20

  const line = (color = [226, 232, 240]) => {
    doc.setDrawColor(...color)
    doc.setLineWidth(0.3)
    doc.line(L, y, R, y)
    y += 5
  }

  const text = (str, x, size = 10, style = 'normal', color = [30, 41, 59]) => {
    doc.setFontSize(size)
    doc.setFont('helvetica', style)
    doc.setTextColor(...color)
    doc.text(str, x, y)
  }

  const wrap = (str, x, maxW, size = 9) => {
    doc.setFontSize(size)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(71, 85, 105)
    const lines = doc.splitTextToSize(str, maxW)
    doc.text(lines, x, y)
    y += lines.length * 4.5
  }

  // Header bar
  doc.setFillColor(15, 23, 42)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text('INVITATION TO TENDER', L, 13)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(148, 163, 184)
  doc.text('AI Tender Management System  ·  Confidential Document', L, 20)
  y = 38

  // Tender ID badge area
  doc.setFillColor(239, 246, 255)
  doc.roundedRect(L, y - 5, W, 14, 2, 2, 'F')
  text(tenderRef(tender), L + 4, 11, 'bold', [37, 99, 235])
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 116, 139)
  doc.text(`Stage: ${tender.stage}`, R - 4, y + 2, { align: 'right' })
  y += 16

  // Title
  text(tender.title, L, 14, 'bold', [15, 23, 42])
  y += 8
  text(`${tender.department}`, L, 9, 'normal', [100, 116, 139])
  y += 8
  line()

  // Key Details grid
  const fields = [
    ['Budget', tender.budget],
    ['Submission Deadline', tender.deadline],
    ['Created', tender.created],
    ['Bidders', String(tender.bidders ?? 0)],
    ...(tender.duration ? [['Contract Duration', tender.duration]] : []),
  ]

  text('KEY DETAILS', L, 8, 'bold', [100, 116, 139])
  y += 6
  const col = W / 2
  fields.forEach((f, i) => {
    const x = i % 2 === 0 ? L : L + col
    if (i % 2 === 0 && i > 0) y += 9
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 116, 139)
    doc.text(f[0].toUpperCase(), x, y)
    doc.setFontSize(9.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 41, 59)
    doc.text(f[1], x, y + 4)
  })
  y += 14
  line()

  // Description
  if (tender.description) {
    text('DESCRIPTION', L, 8, 'bold', [100, 116, 139])
    y += 6
    wrap(tender.description, L, W)
    y += 4
    line()
  }

  // Scope section
  text('STATEMENT OF WORK', L, 8, 'bold', [100, 116, 139])
  y += 6
  const scope = `The Contractor shall provide ${tender.title} for ${tender.department}, encompassing the full design, implementation, testing, and handover of all required deliverables as specified in this Invitation to Tender. The scope includes procurement, installation, integration, user acceptance testing, staff training, and ongoing support and maintenance as per agreed SLA terms.`
  wrap(scope, L, W)
  y += 2
  line()

  // Evaluation criteria
  text('EVALUATION CRITERIA', L, 8, 'bold', [100, 116, 139])
  y += 6
  const criteria = [
    ['Technical Approach & Methodology', '25%'],
    ['Team Qualifications & Experience', '20%'],
    ['Implementation Timeline', '15%'],
    ['Total Bid Price', '40%'],
  ]
  criteria.forEach(([label, weight]) => {
    doc.setFillColor(248, 250, 252)
    doc.rect(L, y - 3, W, 7, 'F')
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(51, 65, 85)
    doc.text(label, L + 3, y + 1)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(37, 99, 235)
    doc.text(weight, R - 3, y + 1, { align: 'right' })
    y += 8
  })
  y += 2
  line()

  // Footer
  doc.setFillColor(248, 250, 252)
  doc.rect(0, 277, 210, 20, 'F')
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(148, 163, 184)
  doc.text(`Generated by TenderAI  ·  ${tenderRef(tender)}  ·  ${new Date().toLocaleDateString('en-GB')}`, 105, 287, { align: 'center' })

  doc.save(`${tender.id}-ITT.pdf`)
}

function reportShell(tender, headerTitle) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const L = 20
  const R = 190
  const W = R - L
  let y = 20

  doc.setFillColor(15, 23, 42)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text(headerTitle, L, 13)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(148, 163, 184)
  doc.text('AI Tender Management System  ·  Confidential Document', L, 20)
  y = 38

  doc.setFillColor(239, 246, 255)
  doc.roundedRect(L, y - 5, W, 14, 2, 2, 'F')
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(37, 99, 235)
  doc.text(tenderRef(tender), L + 4, y + 2)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 116, 139)
  doc.text(`Stage: ${tender.stage}`, R - 4, y + 2, { align: 'right' })
  y += 16

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(15, 23, 42)
  doc.text(tender.title, L, y)
  y += 8
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 116, 139)
  doc.text(tender.department, L, y)
  y += 8
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.3)
  doc.line(L, y, R, y)
  y += 8

  return { doc, L, R, W, y }
}

function reportFooter(doc, tender) {
  doc.setFillColor(248, 250, 252)
  doc.rect(0, 277, 210, 20, 'F')
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(148, 163, 184)
  doc.text(`Generated by TenderAI  ·  ${tenderRef(tender)}  ·  ${new Date().toLocaleDateString('en-GB')}`, 105, 287, { align: 'center' })
}

export function exportPreQualSummaryPDF(tender, qualifiedBidders) {
  const { doc, L, R, W } = reportShell(tender, 'PRE-QUALIFICATION SUMMARY')
  let y = 78

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(100, 116, 139)
  doc.text('FINANCIALLY QUALIFIED BIDDERS', L, y)
  y += 6

  qualifiedBidders.forEach((b, i) => {
    doc.setFillColor(i === 0 ? 236 : 248, i === 0 ? 253 : 250, i === 0 ? 245 : 252)
    doc.rect(L, y - 4, W, 9, 'F')
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.text(`${i + 1}. ${b.name}`, L + 3, y + 1.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(71, 85, 105)
    doc.text(`${b.country} · Financial: ${b.stage4?.result || 'PASS'}`, R - 3, y + 1.5, { align: 'right' })
    y += 10
  })

  // Export failed bidders and their reasons
  const failedBidders = (tender.prequalBidders || []).filter(b => b.droppedAt || (b.stage4 && b.stage4.result !== 'PASS'))
  if (failedBidders.length > 0) {
    y += 10
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(100, 116, 139)
    doc.text('FAILED / REJECTED BIDDERS', L, y)
    y += 6

    failedBidders.forEach(b => {
      // Check for page breaks
      if (y > 250) {
        doc.addPage()
        y = 30
      }

      doc.setFillColor(254, 242, 242) // red-50
      doc.rect(L, y - 4, W, 14, 'F')
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(15, 23, 42)
      doc.text(b.name, L + 3, y + 1.5)

      // Collect reasons
      let failReasons = []
      if (b.stage3Reasons) {
        Object.keys(b.stage3Reasons).forEach(sheet => {
          Object.keys(b.stage3Reasons[sheet]).forEach(crit => {
            if (b.stage3Reasons[sheet][crit]) {
              failReasons.push(`[${sheet.toUpperCase()}] ${b.stage3Reasons[sheet][crit]}`)
            }
          })
        })
      }
      
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(220, 38, 38) // red-600
      let reasonText = failReasons.length > 0 ? `Reasons: ${failReasons.join('; ')}` : (b.droppedAt === 'stage4' || b.stage4?.result !== 'PASS' ? 'Failed Financial Assessment' : 'Failed Pre-Qualification')
      
      // text wrapping
      const splitText = doc.splitTextToSize(reasonText, W - 6)
      doc.text(splitText, L + 3, y + 6)
      
      y += 10 + (splitText.length * 3)
    })
  }

  reportFooter(doc, tender)
  doc.save(`${tender.id}-PreQual-Summary.pdf`)
}

/**
 * Bidder failure reasoning. Serves two evaluations:
 *  - Pre-qualification, which carries its reasons on bidder.stage3Reasons;
 *  - Technical evaluation, which has no such shape, so the caller passes its
 *    scored failures in `technical` — without it a tech bidder would export the
 *    empty "no reasons" fallback.
 * @param {object} tender
 * @param {object} bidder
 * @param {{ threshold?: number, summary?: string, failures?: Array<{
 *   criterion: string, type?: string, kind: 'must'|'clarify',
 *   score: number, maxScore?: number, minScore?: number, band?: string }> }} [technical]
 */
/**
 * @param {object} tender
 * @param {object} bidder
 * @param {object|null} technical  weighted-score failures (Technical Evaluation)
 * @param {object} [opts]
 * @param {object} [opts.reasons]  per-sheet criterion reasons; defaults to the
 *   PQQ round (`stage3Reasons`). Pass `stage4Reasons` for the financial round.
 * @param {string} [opts.heading]  report banner
 * @param {string} [opts.suffix]   filename suffix
 */
export function exportBidderFailReasonsPDF(tender, bidder, technical = null, opts = {}) {
  const {
    reasons: reasonMap = bidder.stage3Reasons,
    heading = 'BIDDER FAILURE REASONING',
    suffix = 'FailReasoning',
  } = opts
  const { doc, L, R, W } = reportShell(tender, heading)
  let y = 78

  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(15, 23, 42)
  doc.text(`Bidder: ${bidder.name}`, L, y)
  y += 6

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 116, 139)
  doc.text([bidder.country, bidder.category].filter(Boolean).join(' · '), L, y)
  y += technical?.summary ? 7 : 12

  if (technical?.summary) {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(51, 65, 85)
    doc.splitTextToSize(technical.summary, W).forEach(l => { doc.text(l, L, y); y += 5 })
    y += 7
  }

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(220, 38, 38)
  doc.text('EVALUATION FAILURES:', L, y)
  y += 8

  let hasReasons = false

  const techFailures = technical?.failures || []
  if (techFailures.length > 0) {
    hasReasons = true
    const threshold = technical?.threshold ?? 2
    techFailures.forEach(f => {
      const max = f.maxScore ?? 3
      const why = f.kind === 'must'
        ? `Mandatory criterion scored ${f.score} against a minimum of ${f.minScore ?? '—'} — the bidder fails on this criterion regardless of the weighted total.`
        : `Scored ${f.score}, at or below the clarification threshold of ${threshold} — a corrected submission is required before the evaluation can be finalised.`
      const detail = f.band ? `${why} Band: ${f.band}.` : why
      const lines = doc.splitTextToSize(`Reason: ${detail}`, W - 6)
      const blockH = 10 + lines.length * 4

      if (y + blockH > 265) { doc.addPage(); y = 30 }

      doc.setFillColor(...(f.kind === 'must' ? [254, 242, 242] : [255, 251, 235]))
      doc.rect(L, y - 4, W, blockH, 'F')

      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(15, 23, 42)
      doc.text(`[${f.kind === 'must' ? 'MUST BELOW MINIMUM' : 'CLARIFICATION'}] ${f.criterion}`, L + 3, y + 1.5)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(71, 85, 105)
      doc.text(`Score ${f.score}/${max}${f.minScore != null ? `  ·  min ${f.minScore}` : ''}`, R - 3, y + 1.5, { align: 'right' })

      doc.setFontSize(8)
      doc.setTextColor(...(f.kind === 'must' ? [220, 38, 38] : [180, 83, 9]))
      doc.text(lines, L + 3, y + 6)

      y += blockH + 4
    })
  }

  if (!hasReasons && reasonMap) {
    Object.keys(reasonMap).forEach(sheet => {
      Object.keys(reasonMap[sheet]).forEach(crit => {
        if (reasonMap[sheet][crit]) {
          hasReasons = true
          
          if (y > 250) {
            doc.addPage()
            y = 30
          }

          doc.setFillColor(254, 242, 242)
          doc.rect(L, y - 4, W, 14, 'F')
          
          doc.setFontSize(9)
          doc.setFont('helvetica', 'bold')
          doc.setTextColor(15, 23, 42)
          doc.text(`[${sheet.toUpperCase()}] Criterion ID: ${crit}`, L + 3, y + 1.5)

          doc.setFontSize(8)
          doc.setFont('helvetica', 'normal')
          doc.setTextColor(220, 38, 38)
          const reasonText = reasonMap[sheet][crit]
          const splitText = doc.splitTextToSize(`Reason: ${reasonText}`, W - 6)
          doc.text(splitText, L + 3, y + 6)
          
          y += 10 + (splitText.length * 4)
        }
      })
    })
  }

  if (!hasReasons) {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 116, 139)
    doc.text(technical
      ? 'No individual criterion failed — the bidder fell short on the overall weighted total only.'
      : 'No specific failure reasons recorded or bidder failed at a different stage.', L, y)
  }

  reportFooter(doc, tender)
  doc.save(`${tender.id}-${bidder.name.replace(/[^a-z0-9]/gi, '_')}-${suffix}.pdf`)
}

/**
 * Procurement Submission Form — Strategy.
 * @param {object} tender
 * @param {object} psf     the generated PSF document (see PsfStrategy.jsx buildPsf)
 */
/**
 * Procurement Submission Form — Strategy.
 *
 * Walks every section of the template rather than a chosen few: the Contract
 * Holder fills in around twenty of them, and an export that quietly carried
 * only the header and the narrative would look complete while dropping the
 * history, every checkbox group, the 21 milestones, the tenderer list and all
 * the ICV rows.
 *
 * @param {object} tender
 * @param {object} psf  the generated PSF document (see PsfStrategy.jsx buildPsf)
 */
export function exportPsfPDF(tender, psf = {}) {
  const { doc, L, W } = reportShell(tender, 'PROCUREMENT SUBMISSION FORM')
  let y = 78

  const page = (needed = 8) => { if (y + needed > 275) { doc.addPage(); y = 30 } }

  const section = (label) => {
    page(14)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(100, 116, 139)
    doc.text(label, L, y)
    y += 7
  }

  const row = (label, value) => {
    page()
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 116, 139)
    doc.text(label, L, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.text(String(value ?? EM_DASH) || EM_DASH, L + W, y, { align: 'right' })
    y += 7
  }

  const paragraph = (text) => {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(51, 65, 85)
    doc.splitTextToSize(String(text || EM_DASH), W).forEach(line => {
      page(6)
      doc.text(line, L, y)
      y += 5
    })
    y += 4
  }

  /* `[x] Ticked` / `[ ] Unticked`, so a reader sees both states. Three to a
     row, matching the template's own columns. */
  const checkboxes = (boxes = []) => {
    const col = W / 3
    boxes.forEach((box, i) => {
      if (i % 3 === 0) page(6)
      doc.setFontSize(8)
      doc.setFont('helvetica', box.checked ? 'bold' : 'normal')
      doc.setTextColor(...(box.checked ? [15, 23, 42] : [148, 163, 184]))
      const text = `[${box.checked ? 'x' : ' '}] ${box.label}`
      doc.text(doc.splitTextToSize(text, col - 3)[0], L + (i % 3) * col, y)
      if (i % 3 === 2 || i === boxes.length - 1) y += 5
    })
    y += 3
  }

  /* A wrapping two-or-three column table. Long requirement text is the reason
     `row()` cannot carry these — it right-aligns a single line. */
  const table = (headers, widths, rows) => {
    // Column left edges: each starts where the previous one ended.
    const xs = [L]
    for (let i = 1; i < widths.length; i++) xs[i] = xs[i - 1] + widths[i - 1] * W
    page(12)
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(100, 116, 139)
    headers.forEach((h, i) => doc.text(h.toUpperCase(), xs[i], y))
    y += 4
    doc.setDrawColor(226, 232, 240)
    doc.line(L, y - 2, L + W, y - 2)

    rows.forEach(cells => {
      const wrapped = cells.map((cell, i) =>
        doc.splitTextToSize(String(cell || EM_DASH), widths[i] * W - 3))
      const height = Math.max(...wrapped.map(w => w.length)) * 4 + 2
      page(height + 4)
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(51, 65, 85)
      wrapped.forEach((linesForCell, i) =>
        linesForCell.forEach((line, n) => doc.text(line, xs[i], y + n * 4)))
      y += height
    })
    y += 4
  }

  section('SUBMISSION TYPE')
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(37, 99, 235)
  doc.text('[X] Strategy      [ ] Strategy Amendment      [ ] Award      [ ] Variation', L, y)
  y += 10

  section('ATTACHMENTS')
  if (!psf.attachments?.length) paragraph(EM_DASH)
  else psf.attachments.forEach((name, i) => row(`${i + 1}.`, name))
  y += 2

  section('SUBMISSION DETAILS')
  PSF_HEADER_FIELDS.forEach(f => row(f.label, psf.header?.[f.key]))
  y += 2

  section('HISTORY')
  ;['previous', 'existing'].forEach(scope => {
    const entry = psf.history?.[scope] || {}
    row(`Award date of ${scope} Contract`, entry.awardDate)
    row(`Expiry date of ${scope} Contract`, entry.expiryDate)
    row(`Contractor Name (${scope})`, entry.contractorName)
    row(`Method of procuring ${scope} Contract`, entry.method)
    row(`ACV (${scope})`, entry.acv)
    if (entry.actualSpend !== undefined) row('Actual Spend', entry.actualSpend)
  })
  row('Current Spend', psf.history?.currentSpend)
  y += 2

  section('REVIEWS / APPROVALS ESTABLISHED')
  checkboxes(psf.reviews)

  PSF_NARRATIVE_FIELDS.forEach(field => {
    section(field.label.toUpperCase())
    paragraph(psf.narrative?.[field.key])
  })

  section('ESTIMATE BASIS')
  row('Confidence Level', psf.estimate?.confidenceLevel)
  checkboxes(psf.estimate?.basis)

  section('BENCHMARKING OF ESTIMATES')
  paragraph(psf.narrative?.benchmarking)

  section('TENDER PLAN')
  checkboxes(psf.tenderPlan?.types)
  row('New services required in place by', psf.tenderPlan?.requiredBy)
  y += 2
  table(
    ['Milestone', 'Planned', 'Actual'],
    [0.56, 0.22, 0.22],
    (psf.tenderPlan?.milestones || []).map(m => [m.label, m.planned, m.actual]),
  )
  section('DEVIATIONS')
  paragraph(psf.tenderPlan?.deviations)

  section('TENDER STRATEGY')
  checkboxes(psf.tenderStrategy)

  section('COMPETITIVE — DROP LIST')
  checkboxes(psf.dropLists?.competitive)
  section('SINGLE SOURCE / OEM — DROP LIST')
  checkboxes(psf.dropLists?.singleSourceOem)

  section('PROPOSED BASIS FOR TENDER ASSESSMENTS')
  row('Technical', psf.assessments?.technical)
  row('Cut Off', psf.assessments?.cutOff)
  row('Commercial', psf.assessments?.commercial)
  y += 2

  section('ALTERNATIVES CONSIDERED')
  paragraph(psf.alternativesConsidered)
  section('OTHER DETAILS')
  paragraph(psf.assessmentOtherDetails)
  section('OMANISATION IMPLICATIONS')
  paragraph(psf.omanisationImplications)
  section('OTHER DETAILS (OMANISATION)')
  paragraph(psf.omanisationOtherDetails)

  section('NEGOTIATION STRATEGY')
  row('Applicability', psf.negotiation?.applicability)
  y += 2
  paragraph(psf.narrative?.negotiationDetails)
  section('ADDITIONAL NOTES')
  paragraph(psf.strategyAdditionalNotes)

  section('TENDERER LIST')
  row('Source of Tenderer List', psf.tendererList?.source)
  y += 2
  table(
    ['S/No.', 'Contractor / Supplier', 'Pre-Qual Result', 'Justification'],
    [0.08, 0.3, 0.2, 0.42],
    (psf.tendererList?.rows || []).map((r, i) => [String(i + 1), r.reference, r.prequalResult, r.justification]),
  )

  section('JUSTIFICATION')
  paragraph(psf.narrative?.tendererJustification)
  section('ADDITIONAL NOTES')
  paragraph(psf.tendererAdditionalNotes)
  section('RECOMMENDATION / REQUEST')
  paragraph(psf.narrative?.recommendation)

  section('ICV REVIEW DETAIL')
  paragraph(psf.icvReviewDetail)
  table(
    ['#', 'Requirement', 'Yes/No · %', 'Justification / Comments'],
    [0.06, 0.44, 0.16, 0.34],
    (psf.icvRequirements || []).map(r => [r.ordinal, r.requirement, r.answer, r.comment]),
  )

  const assignmentBlocks = [
    {
      people: tender.assignedContractEngineers
        || (tender.assignedContractEngineer ? [tender.assignedContractEngineer] : []),
      one: 'ASSIGNED CONTRACT ENGINEER',
      many: 'ASSIGNED CONTRACT ENGINEERS',
    },
    { people: tender.assignedHseOfficers, one: 'ASSIGNED HSE OFFICER', many: 'ASSIGNED HSE OFFICERS' },
    { people: tender.assignedIcvLeads,    one: 'ASSIGNED ICV LEAD',    many: 'ASSIGNED ICV LEADS'    },
  ]
  assignmentBlocks.forEach(({ people, one, many }) => {
    if (!people?.length) return
    y += 4
    section(people.length > 1 ? many : one)
    row(people.map(c => c.name).join(', '), tender.psfCompletedAt || '')
  })

  reportFooter(doc, tender)
  doc.save(`${tender.id}-PSF-Strategy.pdf`)
}

export function exportClosureReportPDF(tender) {
  const { doc, L, W } = reportShell(tender, 'CONTRACT CLOSURE REPORT')
  let y = 78

  const fields = [
    ['Contract Start', tender.contractStartDate || '—'],
    ['Delivery Progress', `${tender.deliveryProgress ?? 100}%`],
    ['Final Budget', tender.budget],
    ['Closure Date', new Date().toLocaleDateString('en-GB')],
  ]
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(100, 116, 139)
  doc.text('CLOSURE DETAILS', L, y)
  y += 7
  fields.forEach(([label, value]) => {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 116, 139)
    doc.text(label, L, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.text(String(value), L + W, y, { align: 'right' })
    y += 7
  })

  reportFooter(doc, tender)
  doc.save(`${tender.id}-Closure-Report.pdf`)
}
